language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
env:
 global:
   - PACKAGE="ipaddr"
 matrix:
   - REVDEPS=true DISTRO=debian-testing OCAML_VERSION=4.06.0
   - DISTRO=debian-testing OCAML_VERSION=4.03.0
   - DISTRO=debian-unstable OCAML_VERSION=4.04.2
   - REVDEPS=true DISTRO=alpine-3.5 OCAML_VERSION=4.04.2
   - DISTRO=debian-stable OCAML_VERSION=4.05.0
   - DISTRO=ubuntu-16.04 OCAML_VERSION=4.05.0
